---

- name: install nginx packages
  apt:
    state: latest
    name:
      - nginx

- name: start nginx
  service:
    name: nginx
    state: started

- name: copy simple index file
  copy:
    src: my_index.html
    dest: /var/www/html/index.html
    mode: 0644
